[ERROR] 2021-08-12 16:20:55,840 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-18"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 41, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:20:56,026 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:20:55.883009-127.0.0.1-767
[ERROR] 2021-08-12 16:22:11,249 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-18"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 34, in cancel
    doc = frappe.get_doc(doctype, name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 840, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 28
    print("//////////////////////////////////////////////////////////////////////////////////////////////////////////////")
        ^
IndentationError: expected an indented block
[ERROR] 2021-08-12 16:22:11,394 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:22:11.249763-127.0.0.1-b3c
[ERROR] 2021-08-12 16:22:45,988 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-18"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 33, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:22:46,127 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:22:45.988744-127.0.0.1-fb7
[ERROR] 2021-08-12 16:24:04,417 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-18"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 33, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:24:04,559 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:24:04.418484-127.0.0.1-990
[ERROR] 2021-08-12 16:24:07,208 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 34, in cancel
    doc = frappe.get_doc(doctype, name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 840, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 16
    if sam:
    ^
IndentationError: unexpected indent
[ERROR] 2021-08-12 16:24:07,618 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:24:07.208942-127.0.0.1-317
[ERROR] 2021-08-12 16:24:12,260 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-18"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 33, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:24:12,281 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:24:12.261381-127.0.0.1-38f
[ERROR] 2021-08-12 16:24:37,725 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',orderss,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:24:37,885 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:24:37.726644-127.0.0.1-67c
[ERROR] 2021-08-12 16:25:08,884 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',self,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:25:09,034 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:25:08.885645-127.0.0.1-78b
[ERROR] 2021-08-12 16:30:37,143 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',orderss,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:30:37,145 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-18"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 33, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:30:37,568 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:30:37.225449-127.0.0.1-072
[ERROR] 2021-08-12 16:30:37,568 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:30:37.224382-127.0.0.1-d74
[ERROR] 2021-08-12 16:31:06,454 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',orderss,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:31:06,467 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:31:06.454981-127.0.0.1-20a
[DEBUG] 2021-08-12 16:31:10,247 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:31:39,794 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:31:39,807 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:31:39.794675-127.0.0.1-cb9
[DEBUG] 2021-08-12 16:32:12,110 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:32:20,662 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabref` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',orderss,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:32:20,675 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:32:20.662782-127.0.0.1-666
[DEBUG] 2021-08-12 16:33:15,387 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:33:37,171 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',orderss,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:33:38,597 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:33:37.315010-127.0.0.1-348
[DEBUG] 2021-08-12 16:34:20,895 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:35:21,817 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:36:24,617 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Order Menu",
 "name": "Order-ID1010"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/order_menu/order_menu.py", line 50, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[DEBUG] 2021-08-12 16:36:25,435 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:36:30,064 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:36:24.833711-127.0.0.1-273
[DEBUG] 2021-08-12 16:37:28,155 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:38:31,855 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:39:33,034 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:40:37,860 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:41:06,018 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',orderss,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:41:08,182 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-18"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 34, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:41:22,712 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:41:06.032039-127.0.0.1-20f
[ERROR] 2021-08-12 16:41:22,713 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:41:08.214997-127.0.0.1-db3
[ERROR] 2021-08-12 16:41:27,343 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',orderss,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:41:27,351 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:41:27.344059-127.0.0.1-30c
[ERROR] 2021-08-12 16:41:31,050 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',orderss,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:41:31,307 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:41:31.143632-127.0.0.1-a98
[ERROR] 2021-08-12 16:41:43,674 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',orderss,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:41:43,682 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:41:43.675357-127.0.0.1-f88
[DEBUG] 2021-08-12 16:41:56,634 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:42:15,126 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',orderss,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:42:15,133 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:42:15.127049-127.0.0.1-a0d
[ERROR] 2021-08-12 16:42:38,476 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Order Menu",
 "name": "Order-ID1011"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/order_menu/order_menu.py", line 50, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:42:38,503 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:42:38.476504-127.0.0.1-605
[ERROR] 2021-08-12 16:42:54,319 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:42:54,325 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:42:54.319762-127.0.0.1-3f5
[DEBUG] 2021-08-12 16:42:57,130 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:43:31,812 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',self,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:43:31,819 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:43:31.812989-127.0.0.1-0e8
[DEBUG] 2021-08-12 16:43:57,783 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:44:09,327 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''',self,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:44:09,335 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:44:09.328369-127.0.0.1-55a
[ERROR] 2021-08-12 16:44:54,050 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="orderss" and r.namee=%s''',self,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:44:54,057 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:44:54.050562-127.0.0.1-e91
[DEBUG] 2021-08-12 16:44:58,700 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:45:59,499 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:46:06,351 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 17, in on_cancel
    cancel_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 23, in cancel_doc
    result =frappe.db.sql('''select p.name from `tabPayments` p, `tabRef` r where r.parent=p.name and r.type="Orderss" and r.namee=%s''')
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%s' at line 1")
[ERROR] 2021-08-12 16:46:07,539 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:46:06.372737-127.0.0.1-5d2
[ERROR] 2021-08-12 16:46:10,896 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:46:10.885317-127.0.0.1-f20
[DEBUG] 2021-08-12 16:46:59,902 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:48:00,442 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:49:01,284 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:50:07,015 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:51:07,262 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:52:07,509 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:53:07,726 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:54:07,935 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:55:08,184 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:56:08,428 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:57:08,641 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:58:08,846 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
