[DEBUG] 2021-08-13 15:47:29,356 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:48:04,393 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.insert_user",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 38, in insert_user
    "doctype": "Payments","payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 699, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/create_new.py", line 18, in get_new_doc
    if doctype not in frappe.local.new_doc_templates:
TypeError: unhashable type: 'dict'
[ERROR] 2021-08-13 15:48:05,709 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.insert_user",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 38, in insert_user
    "doctype": "Payments","payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 699, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/create_new.py", line 18, in get_new_doc
    if doctype not in frappe.local.new_doc_templates:
TypeError: unhashable type: 'dict'
[ERROR] 2021-08-13 15:48:06,110 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:48:05.710623-127.0.0.1-d43
[DEBUG] 2021-08-13 15:48:29,581 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 15:49:29,738 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:49:58,416 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.insert_user",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 38, in insert_user
    "doctype": "Payments","payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 699, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/create_new.py", line 18, in get_new_doc
    if doctype not in frappe.local.new_doc_templates:
TypeError: unhashable type: 'dict'
[ERROR] 2021-08-13 15:49:58,820 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:49:58.417200-127.0.0.1-a7a
[DEBUG] 2021-08-13 15:50:29,930 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:51:13,843 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.insert_user",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 38, in insert_user
    "doctype": "Payments","payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 699, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/create_new.py", line 18, in get_new_doc
    if doctype not in frappe.local.new_doc_templates:
TypeError: unhashable type: 'dict'
[ERROR] 2021-08-13 15:51:14,251 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:51:13.843801-127.0.0.1-801
[DEBUG] 2021-08-13 15:51:30,166 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 15:52:30,353 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:53:22,157 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:53:22,367 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:53:22.158268-127.0.0.1-d8a
[DEBUG] 2021-08-13 15:53:30,533 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:53:58,595 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":cur_frm.doc.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
NameError: global name 'cur_frm' is not defined
[ERROR] 2021-08-13 15:53:59,741 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":cur_frm.doc.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
NameError: global name 'cur_frm' is not defined
[ERROR] 2021-08-13 15:54:00,161 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:53:59.742216-127.0.0.1-730
[ERROR] 2021-08-13 15:54:19,940 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:54:20,339 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:54:19.941297-127.0.0.1-7d8
[DEBUG] 2021-08-13 15:54:30,731 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:55:16,346 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cached_timestamp": "",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Orderss",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
    meta = FormMeta(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
    self.load_templates()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/meta.py", line 179, in load_templates
    module = load_doctype_module(self.name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 840, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 44
    }})
     ^
SyntaxError: invalid syntax
[ERROR] 2021-08-13 15:55:16,591 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:55:16.346658-127.0.0.1-6d9
[DEBUG] 2021-08-13 15:55:30,923 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:55:37,391 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:55:37,647 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:55:37.404303-127.0.0.1-625
[ERROR] 2021-08-13 15:56:07,984 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 699, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/create_new.py", line 18, in get_new_doc
    if doctype not in frappe.local.new_doc_templates:
TypeError: unhashable type: 'dict'
[ERROR] 2021-08-13 15:56:10,096 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 699, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/create_new.py", line 18, in get_new_doc
    if doctype not in frappe.local.new_doc_templates:
TypeError: unhashable type: 'dict'
[ERROR] 2021-08-13 15:56:10,236 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:56:10.096798-127.0.0.1-6b3
[ERROR] 2021-08-13 15:56:27,086 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:56:27,499 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:56:27.087276-127.0.0.1-c2d
[DEBUG] 2021-08-13 15:56:31,154 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 15:57:31,359 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 15:57:41,010 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:57:41,417 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:57:41.010834-127.0.0.1-a27
[ERROR] 2021-08-13 15:57:48,027 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:57:48,031 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:57:48.027520-127.0.0.1-250
[ERROR] 2021-08-13 15:57:50,973 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 43, in new_entry
    "doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160"
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:57:50,977 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:57:50.973911-127.0.0.1-302
[ERROR] 2021-08-13 15:58:15,071 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    frappe.throw(self.customer_name)
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:58:15,480 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:58:15.072224-127.0.0.1-b0a
[ERROR] 2021-08-13 15:58:30,268 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    frappe.throw(self.customer_name)
AttributeError: 'unicode' object has no attribute 'customer_name'
[ERROR] 2021-08-13 15:58:30,273 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 15:58:30.269079-127.0.0.1-879
[DEBUG] 2021-08-13 15:58:31,557 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 15:59:31,745 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:00:31,962 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:01:32,152 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:02:32,358 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:02:39,612 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:02:39,749 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:02:39.612731-127.0.0.1-d7b
[ERROR] 2021-08-13 16:03:13,999 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.db.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'MariaDBDatabase' object has no attribute 'get_doc'
[ERROR] 2021-08-13 16:03:14,169 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:03:14.000244-127.0.0.1-3b9
[ERROR] 2021-08-13 16:03:16,574 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.db.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'MariaDBDatabase' object has no attribute 'get_doc'
[ERROR] 2021-08-13 16:03:16,979 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:03:16.575752-127.0.0.1-ac8
[DEBUG] 2021-08-13 16:03:32,547 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:03:37,291 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:03:37,709 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:03:37.292682-127.0.0.1-b88
[ERROR] 2021-08-13 16:04:24,837 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 42, in new_entry
    frappe.throw(re.customer_name)
AttributeError: 'NoneType' object has no attribute 'customer_name'
[ERROR] 2021-08-13 16:04:24,988 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:04:24.838246-127.0.0.1-f34
[DEBUG] 2021-08-13 16:04:32,756 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:05:02,712 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_all(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1338, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1311, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
ProgrammingError: (u'DocType', u'ORD027')
[ERROR] 2021-08-13 16:05:03,123 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:05:02.714053-127.0.0.1-6b9
[DEBUG] 2021-08-13 16:05:33,034 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:05:35,428 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_all(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1338, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1311, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
ProgrammingError: (u'DocType', u'ORD027')
[ERROR] 2021-08-13 16:05:35,582 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:05:35.429347-127.0.0.1-de2
[ERROR] 2021-08-13 16:06:22,572 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:06:24,241 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:06:24,695 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:06:24.242282-127.0.0.1-2dc
[DEBUG] 2021-08-13 16:06:33,275 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:06:57,736 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:06:58,552 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:06:57.737027-127.0.0.1-a42
[DEBUG] 2021-08-13 16:07:33,521 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:07:42,057 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    re = frappe.get_single(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 785, in get_single
    return get_doc(doctype, doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:07:42,220 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:07:42.058146-127.0.0.1-acc
[DEBUG] 2021-08-13 16:08:33,731 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:09:34,128 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:10:01,871 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:10:02,289 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:10:01.872229-127.0.0.1-694
[DEBUG] 2021-08-13 16:10:34,310 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:11:34,489 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:12:34,717 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:13:34,907 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:14:35,076 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:15:35,286 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:16:35,503 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:17:35,778 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:18:26,629 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_all(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1338, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1311, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
ProgrammingError: (u'DocType', u'ORD027')
[ERROR] 2021-08-13 16:18:27,049 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:18:26.630800-127.0.0.1-4b8
[DEBUG] 2021-08-13 16:18:35,978 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:19:01,944 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.db.get_all(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 528, in get_all
    return frappe.get_all(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1338, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1311, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
ProgrammingError: (u'DocType', u'ORD027')
[ERROR] 2021-08-13 16:19:02,360 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:19:01.945160-127.0.0.1-000
[ERROR] 2021-08-13 16:19:31,819 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 42, in new_entry
    frappe.throw(ret.customer_name)
AttributeError: 'NoneType' object has no attribute 'customer_name'
[ERROR] 2021-08-13 16:19:32,229 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:19:31.820861-127.0.0.1-02d
[DEBUG] 2021-08-13 16:19:36,183 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:19:53,890 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.db.get_list(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1311, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
ProgrammingError: (u'DocType', u'ORD027')
[ERROR] 2021-08-13 16:19:54,307 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:19:53.891568-127.0.0.1-f67
[DEBUG] 2021-08-13 16:20:36,394 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:21:03,881 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:21:04,035 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:21:03.882357-127.0.0.1-04f
[ERROR] 2021-08-13 16:21:24,485 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.db.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'MariaDBDatabase' object has no attribute 'get_doc'
[ERROR] 2021-08-13 16:21:24,906 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:21:24.486687-127.0.0.1-ff3
[DEBUG] 2021-08-13 16:21:36,559 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:22:08,729 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:22:08,878 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:22:08.730333-127.0.0.1-a65
[DEBUG] 2021-08-13 16:22:36,783 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:23:05,555 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:23:05,974 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:23:05.555894-127.0.0.1-823
[DEBUG] 2021-08-13 16:23:36,979 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:24:02,925 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = doc.get(self)
NameError: global name 'doc' is not defined
[ERROR] 2021-08-13 16:24:03,072 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:24:02.925943-127.0.0.1-e1f
[DEBUG] 2021-08-13 16:24:37,213 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:25:31,196 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_doctype(self)
AttributeError: 'module' object has no attribute 'get_doctype'
[ERROR] 2021-08-13 16:25:31,358 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:25:31.196796-127.0.0.1-0c8
[DEBUG] 2021-08-13 16:25:37,404 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:26:31,826 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_list(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1311, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
ProgrammingError: (u'DocType', u'ORD027')
[ERROR] 2021-08-13 16:26:31,977 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:26:31.827581-127.0.0.1-b27
[DEBUG] 2021-08-13 16:26:37,599 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:26:55,162 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:26:55,575 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:26:55.162999-127.0.0.1-6e7
[DEBUG] 2021-08-13 16:27:37,791 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:28:37,992 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-13 16:29:38,527 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-13 16:29:49,013 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "args": "",
 "cmd": "frappe.model.mapper.make_mapped_doc",
 "method": "employee_management.employee_management.doctype.orderss.orderss.new_entry",
 "selected_children": "{}",
 "source_name": "ORD027"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 41, in new_entry
    ret = frappe.get_doc(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for ORD027 (frappe.core.doctype.ord027.ord027 Error: No module named ord027.ord027)
[ERROR] 2021-08-13 16:29:49,152 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-13 16:29:49.013792-127.0.0.1-875
[DEBUG] 2021-08-13 16:30:38,722 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
