[DEBUG] 2021-08-12 15:51:22,132 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 15:52:02,219 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 21, in on_cancel
    delete_user(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 25, in delete_user
    payments=frappe.db.sql('''select p.name,p.posting_date,p.paid_amount,r.outstanding_amount from `tabPayments` p, `tabOrderss` r where r.parent=p.name and r.reference_doctype="Orderss" and r.reference_name=%s''',self,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 15:52:02,369 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:52:02.220230-127.0.0.1-2cc
[ERROR] 2021-08-12 15:52:17,791 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-09"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 28, in on_cancel
    print(paument.get(u'name'))
NameError: global name 'paument' is not defined
[ERROR] 2021-08-12 15:52:17,932 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:52:17.791797-127.0.0.1-d97
[DEBUG] 2021-08-12 15:52:22,352 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 15:52:47,428 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-09"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 28, in on_cancel
    print(payment.get(u'name'))
NameError: global name 'payment' is not defined
[ERROR] 2021-08-12 15:52:47,570 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:52:47.428876-127.0.0.1-a5b
[ERROR] 2021-08-12 15:53:08,310 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-09"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 28, in on_cancel
    print(payments.get(u'name'))
AttributeError: 'list' object has no attribute 'get'
[ERROR] 2021-08-12 15:53:08,452 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:53:08.311024-127.0.0.1-436
[ERROR] 2021-08-12 15:53:13,256 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 34, in cancel
    doc = frappe.get_doc(doctype, name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 840, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 29
    @frappe.whitelist(allow_guest=True)
    ^
IndentationError: expected an indented block
[ERROR] 2021-08-12 15:53:13,399 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:53:13.257070-127.0.0.1-9ab
[DEBUG] 2021-08-12 15:53:22,552 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 15:53:52,300 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-09"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 28, in on_cancel
    print(payments[0].get(u'name'))
IndexError: list index out of range
[ERROR] 2021-08-12 15:53:52,441 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:53:52.301579-127.0.0.1-c7f
[DEBUG] 2021-08-12 15:54:22,762 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 15:54:28,431 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Order Menu",
 "name": "Order-ID1009"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/order_menu/order_menu.py", line 44, in on_cancel
    for d in len(payments):
TypeError: 'int' object is not iterable
[ERROR] 2021-08-12 15:54:28,848 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:54:28.432753-127.0.0.1-076
[ERROR] 2021-08-12 15:54:29,074 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-09"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 28, in on_cancel
    print(payments[0])
IndexError: list index out of range
[ERROR] 2021-08-12 15:54:29,086 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:54:29.075075-127.0.0.1-a21
[DEBUG] 2021-08-12 15:55:22,951 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 15:56:23,173 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 15:57:23,471 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 15:57:25,114 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 34, in cancel
    doc = frappe.get_doc(doctype, name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 840, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 39
    result = frappe.db.sql(''' select)
	



@frappe.whitelist(allow_guest=True)
def insert_user(self):
	from frappe.utils import random_string
	result= frappe.get_doc({
			"doctype": "Payments","customer_name":self.customer_name,"payment_type":"Pay","payment_mode":"Cash","paid_amount":"160",
		})
	result.append("ref",{"type":"Orderss","namee":self.name,})
	result.submit()
                                      
	



                                   
                      
	                                      
	                        
			                                                                                                                        
		  
	                                                          
	              ^
SyntaxError: EOF while scanning triple-quoted string literal
[ERROR] 2021-08-12 15:57:25,256 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:57:25.115253-127.0.0.1-807
[ERROR] 2021-08-12 15:58:17,110 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Order Menu",
 "name": "Order-ID1010"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/order_menu/order_menu.py", line 49, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 15:58:17,255 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 15:58:17.111526-127.0.0.1-1a5
[DEBUG] 2021-08-12 15:58:23,661 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 15:59:23,896 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:00:24,146 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:01:01,845 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Order Menu",
 "name": "Order-ID1010"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 34, in cancel
    doc = frappe.get_doc(doctype, name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 765, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 69, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/base_document.py", line 48, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 840, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/order_menu/order_menu.py", line 49
    doc.docstatus :2
                  ^
SyntaxError: invalid syntax
[ERROR] 2021-08-12 16:01:02,396 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:01:01.847850-127.0.0.1-c4d
[ERROR] 2021-08-12 16:01:04,553 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-09-2"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 30, in on_cancel
    print(e.get(name))
NameError: global name 'name' is not defined
[ERROR] 2021-08-12 16:01:04,561 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:01:04.554205-127.0.0.1-d4d
[DEBUG] 2021-08-12 16:01:24,340 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:01:38,921 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Order Menu",
 "name": "Order-ID1010"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/order_menu/order_menu.py", line 49, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:01:39,067 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:01:38.922167-127.0.0.1-286
[DEBUG] 2021-08-12 16:02:24,529 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:02:40,246 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 21, in on_cancel
    delete_user(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 26, in delete_user
    result =payments=frappe.db.sql('''select p.name,p.posting_date,p.paid_amount,r.outstanding_amount from `tabPayment Entry` p, `tabPayment Reference` r where r.parent=p.name and r.reference_doctype="Order" and r.reference_name=%s''',order,as_dict=1)
NameError: global name 'order' is not defined
[ERROR] 2021-08-12 16:02:40,387 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:02:40.247653-127.0.0.1-3b2
[ERROR] 2021-08-12 16:02:40,677 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Order Menu",
 "name": "Order-ID1010"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/order_menu/order_menu.py", line 50, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:02:40,687 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:02:40.677555-127.0.0.1-229
[ERROR] 2021-08-12 16:03:10,578 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 21, in on_cancel
    delete_user(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 26, in delete_user
    result =payments=frappe.db.sql('''select p.name,p.posting_date,p.paid_amount,r.outstanding_amount from `tabPayment Entry` p, `tabPayment Reference` r where r.parent=p.name and r.reference_doctype="Order" and r.reference_name=%s''',self,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:03:10,732 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:03:10.579237-127.0.0.1-823
[DEBUG] 2021-08-12 16:03:24,769 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:04:24,990 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:05:25,168 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:05:39,290 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 21, in on_cancel
    delete_user(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 26, in delete_user
    result =payments=frappe.db.sql('''select p.name,p.posting_date,p.paid_amount,r.outstanding_amount from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Order" and r.reference_name=%s''',self,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:05:39,437 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:05:39.290962-127.0.0.1-bb4
[ERROR] 2021-08-12 16:06:23,337 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 21, in on_cancel
    delete_user(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 26, in delete_user
    result =payments=frappe.db.sql('''select p.name,p.posting_date,p.paid_amount,r.outstanding_amount from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Order" and r.reference_name=%s''',orderss,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:06:23,758 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:06:23.338318-127.0.0.1-e3c
[DEBUG] 2021-08-12 16:06:25,358 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:06:51,172 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 21, in on_cancel
    delete_user(self)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 26, in delete_user
    result =frappe.db.sql('''select p.name,p.posting_date,p.paid_amount,r.outstanding_amount from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Order" and r.reference_name=%s''',orderss,as_dict=1)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/server-admin/Projects/Gopi/Training/env/local/lib/python2.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Orderss' object has no attribute 'translate'
[ERROR] 2021-08-12 16:06:51,324 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:06:51.173598-127.0.0.1-db2
[DEBUG] 2021-08-12 16:07:25,534 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:08:25,762 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:09:02,443 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Orderss",
 "name": "ORD007"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/orderss/orderss.py", line 21, in on_cancel
    result =frappe.db.sql('''select p.name,p.posting_date,p.paid_amount,r.outstanding_amount from `tabPayments` p, `tabRef` r where r.parent=p.name and r.reference_doctype="Order" and r.reference_name=%s''',orderss,as_dict=1)
NameError: global name 'orderss' is not defined
[ERROR] 2021-08-12 16:09:02,860 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:09:02.444669-127.0.0.1-d7d
[DEBUG] 2021-08-12 16:09:25,952 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:10:26,164 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:11:26,371 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:11:41,751 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 34, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:11:41,912 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:11:41.751848-127.0.0.1-6c0
[DEBUG] 2021-08-12 16:12:26,590 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:13:26,776 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:14:21,179 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 31, in on_cancel
    {"doctype": "Payment Detail", "name": e.get(u'name')})
NameError: global name 'e' is not defined
[ERROR] 2021-08-12 16:14:21,319 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:14:21.180303-127.0.0.1-910
[DEBUG] 2021-08-12 16:14:27,017 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:14:34,780 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 33, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:14:34,936 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:14:34.780652-127.0.0.1-bf1
[DEBUG] 2021-08-12 16:15:27,198 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:15:44,852 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 33, in on_cancel
    docc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:15:45,014 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:15:44.852967-127.0.0.1-f42
[DEBUG] 2021-08-12 16:16:27,482 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:17:12,501 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 41, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:17:12,642 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:17:12.502285-127.0.0.1-52d
[DEBUG] 2021-08-12 16:17:27,682 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:17:58,162 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 41, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:17:58,310 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:17:58.163366-127.0.0.1-f77
[DEBUG] 2021-08-12 16:18:27,862 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:18:56,875 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 41, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:18:56,885 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:18:56.875719-127.0.0.1-1bf
[DEBUG] 2021-08-12 16:19:28,049 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[ERROR] 2021-08-12 16:19:54,783 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py:
Site: management
Form Dict: {
 "cmd": "frappe.desk.form.save.cancel",
 "doctype": "Wallet Transaction",
 "name": "WE-17"
}
Request Error
Traceback (most recent call last):
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/__init__.py", line 1075, in call
    return fn(*args, **newargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 877, in cancel
    self._cancel()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 867, in _cancel
    self.save()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 937, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1078, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 1061, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/server-admin/Projects/Gopi/Training/apps/employee_management/employee_management/employee_management/doctype/wallet_transaction/wallet_transaction.py", line 41, in on_cancel
    doc.update()
TypeError: update() takes exactly 2 arguments (1 given)
[ERROR] 2021-08-12 16:19:54,924 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-08-12 16:19:54.783887-127.0.0.1-d9a
[DEBUG] 2021-08-12 16:20:28,274 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:21:28,452 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:22:28,636 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:23:28,845 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:24:29,053 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
[DEBUG] 2021-08-12 16:25:29,242 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/scheduler.py:
Site: management
Queued events for site management
